### ISSUE TITLE
False positives?

### ISSUE THREAD

**Issue by justTOBBI** [svenstaro/genact#211]
When you scan the windows binaries on virustotal 5 scanners detect a trojan. Are these false positives or is this actual malware? 
With these Terminal applications this happens quite often to me that these get flagged.

https://www.virustotal.com/gui/file/1b0f075b0f0a30ec78784bd4722f606cf33d11577aedf62d2c336cd0eb65c946/detection

![grafik](https://user-images.githubusercontent.com/47004621/113999162-11520a80-985a-11eb-8616-a5804d4ad0a1.png)

**Comment by svenstaro** [comment]
These binaries are entirely made in CI and you can have a look at exactly how they are made. They are also packed using `upx` which I suppose many scanners might pick up as being malware. If in doubt, compile them yourself and pack them using `upx`. Since the binaries are reproducible, you should end up with the exact same hash and then you know that you can trust these binaries.

**Comment by justTOBBI** [comment]
Makes sense to me. 
Thanks for you quick reply :)
